version: "3.3"

services:
  mojaloop-simulator-ui:
    build:
      context: .
      dockerfile: Dockerfile
    image: mojaloop-simulator-ui
    tty: true
    stdin_open: true  
    ports:
     - "80:8080"
    restart: always
    